# Generated by Django 4.2.7 on 2024-02-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.job'),
        ),
    ]
